#!/bin/bash

# Helper script to find your cPanel server IP address
# This script provides multiple methods to locate the IP

echo "🔍 Finding cPanel Server IP Address"
echo "===================================="
echo ""

echo "Method 1: Check GitHub Secrets (requires GitHub CLI)"
echo "-----------------------------------------------------"
echo "Your CPANEL_HOST secret is configured in GitHub."
echo "To view it (if you have permissions):"
echo ""
echo "  gh secret get CPANEL_HOST --repo KishoreKu/gubbu-api"
echo ""
echo "Note: GitHub secrets are encrypted and may not be retrievable."
echo ""

echo "Method 2: Check cPanel Dashboard"
echo "---------------------------------"
echo "1. Log into your cPanel hosting account"
echo "2. Look for 'Server Information' in the left sidebar"
echo "3. Find 'Shared IP Address' or 'Server IP'"
echo ""

echo "Method 3: Check Hosting Provider Email"
echo "---------------------------------------"
echo "Search your email for:"
echo "  - 'Welcome to cPanel' or 'Hosting Account Created'"
echo "  - Look for 'Server IP' or 'Name Server' information"
echo ""

echo "Method 4: SSH into Server (if you have SSH access)"
echo "---------------------------------------------------"
echo "If you know the cPanel hostname, try:"
echo ""
echo "  ssh alajangi@[CPANEL_HOST]"
echo "  hostname -I"
echo ""
echo "Or from outside:"
echo ""
echo "  nslookup [CPANEL_HOST]"
echo "  dig [CPANEL_HOST] +short"
echo ""

echo "Method 5: Check Old DNS Records"
echo "--------------------------------"
echo "If api.gubbu.io previously worked, check DNS history:"
echo ""
echo "  https://securitytrails.com/domain/gubbu.io/history/a"
echo ""

echo "Method 6: Contact Hosting Provider"
echo "-----------------------------------"
echo "Contact your cPanel hosting provider support and ask for:"
echo "  - Server IP address for account 'alajangi'"
echo "  - Shared IP address for the hosting account"
echo ""

echo "===================================="
echo ""
echo "Once you have the IP address, add it to Namecheap:"
echo ""
echo "  1. Log into Namecheap"
echo "  2. Domain List → Manage gubbu.io → Advanced DNS"
echo "  3. Add A Record:"
echo "     - Host: api"
echo "     - Value: [Your cPanel Server IP]"
echo "     - TTL: Automatic"
echo ""
echo "Then verify with:"
echo "  ./scripts/verify-connectivity.sh"
echo ""
